version: '2.4'

volumes:
  orderer.example.com:
  peer0.org1.example.com:
  peer0.org2.example.com:

networks:
  test:
    name: fabric_test

services:

  orderer.example.com:
    container_name: orderer
    image: hyperledger/fabric-orderer:2.3
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
    command: orderer
    volumes:
      - type: bind
        source: ../config/orderer.yaml
        target: /etc/hyperledger/fabric/orderer.yaml
      - ../organizations/orderer/orderer:/var/hyperledger/orderer
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
    networks:
      - test

  peer0.org1.example.com:
    container_name: o1p0
    image: hyperledger/fabric-peer:2.3
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - type: bind
        source: ../config/core.yaml
        target: /etc/hyperledger/fabric/core.yaml
      - ../organizations/org1/peer0:/etc/hyperledger/fabric
      - peer0.org1.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - test

  peer0.org2.example.com:
    container_name: o2p0
    image: hyperledger/fabric-peer:2.3
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - type: bind
        source: ../config/core.yaml
        target: /etc/hyperledger/fabric/core.yaml
      - ../organizations/org2/peer0:/etc/hyperledger/fabric
      - peer0.org2.example.com:/var/hyperledger/production
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - test
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations:/peer/organizations
      - ../scripts:/peer/scripts/
    depends_on:
      - peer0.org1.example.com
      - peer0.org2.example.com
    networks:
      - test
