name: Build/release

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - working-directory: ./fabric/frontend
        run: yarn && yarn build

      - working-directory: ./fabric/electron
        run: yarn && yarn build
