name: Build/release

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - working-directory: ./fabric/frontend
        run: yarn && yarn build

      - working-directory: ./fabric/electron
        run: yarn && yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./fabric/electron/build
